# Generated by Django 5.0.4 on 2024-04-16 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateDodo',
            new_name='Update',
        ),
    ]
