# Generated by Django 5.0.4 on 2024-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_dodo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dodo',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='dodo',
            name='dodo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dodo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
