# Generated by Django 5.0.2 on 2024-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_dodo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodo',
            name='alive',
            field=models.BooleanField(default=None),
        ),
    ]
