# Generated by Django 5.0.2 on 2024-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_dodo_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodo',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
