# Generated by Django 5.0.4 on 2024-04-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_dodo_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='dodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='base.dodo'),
        ),
    ]
